/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OFirmieRouteImport } from './routes/o-firmie'
import { Route as RealizacjeRouteImport } from './routes/realizacje'
import { Route as UslugiIndexRouteImport } from './routes/uslugi.index'
import { Route as UslugiSlugRouteImport } from './routes/uslugi.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OFirmieRoute = OFirmieRouteImport.update({
  id: '/o-firmie',
  path: '/o-firmie',
  getParentRoute: () => rootRouteImport,
} as any)
const RealizacjeRoute = RealizacjeRouteImport.update({
  id: '/realizacje',
  path: '/realizacje',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiIndexRoute = UslugiIndexRouteImport.update({
  id: '/uslugi/',
  path: '/uslugi/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiSlugRoute = UslugiSlugRouteImport.update({
  id: '/uslugi/$slug',
  path: '/uslugi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-firmie': typeof OFirmieRoute
  '/realizacje': typeof RealizacjeRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-firmie': typeof OFirmieRoute
  '/realizacje': typeof RealizacjeRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi': typeof UslugiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-firmie': typeof OFirmieRoute
  '/realizacje': typeof RealizacjeRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/o-firmie'
    | '/realizacje'
    | '/uslugi/$slug'
    | '/uslugi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/kontakt' | '/o-firmie' | '/realizacje' | '/uslugi/$slug' | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/o-firmie'
    | '/realizacje'
    | '/uslugi/$slug'
    | '/uslugi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  OFirmieRoute: typeof OFirmieRoute
  RealizacjeRoute: typeof RealizacjeRoute
  UslugiSlugRoute: typeof UslugiSlugRoute
  UslugiIndexRoute: typeof UslugiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-firmie': {
      id: '/o-firmie'
      path: '/o-firmie'
      fullPath: '/o-firmie'
      preLoaderRoute: typeof OFirmieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realizacje': {
      id: '/realizacje'
      path: '/realizacje'
      fullPath: '/realizacje'
      preLoaderRoute: typeof RealizacjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/': {
      id: '/uslugi/'
      path: '/uslugi'
      fullPath: '/uslugi/'
      preLoaderRoute: typeof UslugiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/$slug': {
      id: '/uslugi/$slug'
      path: '/uslugi/$slug'
      fullPath: '/uslugi/$slug'
      preLoaderRoute: typeof UslugiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  OFirmieRoute: OFirmieRoute,
  RealizacjeRoute: RealizacjeRoute,
  UslugiSlugRoute: UslugiSlugRoute,
  UslugiIndexRoute: UslugiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
